package com.example.assignment;

public class CountryDatabase {

    int[] flags = {
        R.drawable.afghanistan,
        R.drawable.argentina,
        R.drawable.australia,
        R.drawable.bahrain,
        R.drawable.bangladesh,
        R.drawable.belgium,
        R.drawable.bhutan,
        R.drawable.brazil,
        R.drawable.cambodia,
        R.drawable.cameroon,
        R.drawable.canada,
        R.drawable.chile,
        R.drawable.china,
        R.drawable.colombia,
        R.drawable.croatia,
        R.drawable.cuba,
        R.drawable.denmark,
        R.drawable.egypt,
        R.drawable.fiji,
        R.drawable.finland,
        R.drawable.france,
        R.drawable.germany,
        R.drawable.ghana,
        R.drawable.iceland,
        R.drawable.india,
        R.drawable.indonesia,
        R.drawable.iran,
        R.drawable.iraq,
        R.drawable.ireland,
        R.drawable.israel,
        R.drawable.italy,
        R.drawable.jamaica,
        R.drawable.japan,
        R.drawable.jordan,
        R.drawable.kenya,
        R.drawable.malaysia,
        R.drawable.maldives,
        R.drawable.mexico,
        R.drawable.nepal,
        R.drawable.netherlands,
        R.drawable.newzealand,
        R.drawable.northkorea,
        R.drawable.norway,
        R.drawable.pakistan,
        R.drawable.phillipines,
        R.drawable.portugal,
        R.drawable.qatar,
        R.drawable.russia,
        R.drawable.saudiarabia,
        R.drawable.singapore,
        R.drawable.southafrica,
        R.drawable.southkorea,
        R.drawable.spain,
        R.drawable.srilanka,
        R.drawable.sweden,
        R.drawable.switzerland,
        R.drawable.syria,
        R.drawable.thailand,
        R.drawable.turkey,
        R.drawable.uae,
        R.drawable.uk,
        R.drawable.uruguay,
        R.drawable.usa,
        R.drawable.vietnam,
        R.drawable.zimbabwe,

    };

    String[] answers = {
            "Afghanistan",
            "Argentina",
            "Australia",
            "Bahrain",
            "Bangladesh",
            "Belgium",
            "Bhutan",
            "Brazil",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Chile",
            "China",
            "Colombia",
            "Croatia",
            "Cuba",
            "Denmark",
            "Egypt",
            "Fiji",
            "Finland",
            "France",
            "Germany",
            "Ghana",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kenya",
            "Malaysia",
            "Maldives",
            "Mexico",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "North Korea",
            "Norway",
            "Pakistan",
            "Phillipines",
            "Portugal",
            "Qatar",
            "Russia",
            "Saudi Arabia",
            "Singapore",
            "South Africa",
            "South Korea",
            "Spain",
            "Sri Lanka",
            "Sweden",
            "Switzerland",
            "Syria",
            "Thailand",
            "Turkey",
            "UAE",
            "UK",
            "Uruguay",
            "Usa",
            "Vietnam",
            "Zimbabwe",


    };

}
